### ISSUE TITLE
Embed query searches in URLs so that searches can be shared directly

### ISSUE THREAD

**Issue by LewisHaley** [asimihsan/tablequeryjs#18]
Rather that having give a URL and a string to input as a filter, allow
users to give a single URL which contains instructions for `tablequeryjs`
to immediately create a search/filter. For example, this would be similar
to doing `http://en.wikipedia.org/wiki/Git_hub#Description` to immediately
direct the user to the `Description` section.

**Comment by asimihsan** [comment]
This is fixed by release v0.1.7. Please see: https://github.com/asimihsan/tablequeryjs/releases/tag/v0.1.7.

I'll close once `jsdelivr` push v0.1.7 to their CDN.

**Comment by asimihsan** [comment]
It's up, closing.
