### ISSUE TITLE
bug: column with "75b1f2c" isn't searchable (test case attached)

### ISSUE THREAD

**Issue by drothlis** [asimihsan/tablequeryjs#19]
Test case: http://david.rothlis.net/tablequerytestcase.html

| type this into the filter | expected result | actual result |
|----|----|----|
| `test_that_column_A_matches` | Both rows match | ✖ No rows match |
| `75b1f2c` | The first row matches | ✖ No rows match |
| `test_that_column_B_matches` | Both rows match | ✓ Both rows match |

**Comment by asimihsan** [comment]
Fixed and regression tested by v0.1.6, please see https://github.com/asimihsan/tablequeryjs/releases/tag/v0.1.6.

It's likely there are other bugs like this still in tablequeryjs. Thanks for your test case, it was exactly what I needed and used as a regression test.
