### ISSUE TITLE
tablequery.js leaks `_` (Lo-Dash) to global namespace

### ISSUE THREAD

**Issue by drothlis** [asimihsan/tablequeryjs#20]
Testcase: http://david.rothlis.net/tablequery-leaks-lodash-testcase.html
(the testcase pops up an alert that prints `_.VERSION`).

If you open the above testcase in Firefox with Firebug, type `_` into the console, and click on the resulting value, Firebug takes you to the tablequery.js source code.

**Comment by drothlis** [comment]
It's possibly [this line|https://github.com/asimihsan/tablequeryjs/blob/743571da/src/tablequery-core.js#L41]? (I'm only speculating)

**Comment by asimihsan** [comment]
Fixed and regression tested by v0.1.6 release, please see: https://github.com/asimihsan/tablequeryjs/releases/tag/v0.1.6.
