### ISSUE TITLE
Publish unminified version to the CDN

### ISSUE THREAD

**Issue by drothlis** [asimihsan/tablequeryjs#22]
The CDN referenced in the README only seems to contain a minified version. This makes debugging issues very hard. (I haven't been able to build it myself, no doubt due to my ignorance of webby build tools.)

**Comment by asimihsan** [comment]
Not sure if I can get to this this week but yes the CDN only has the minified version. I'll open a pull request for jsDelivr to publish an unminified version.

(The fully correct way of allowing minified scripts to be debuggable is to publish source map files, i.e. http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/. I don't have experience with source map files but after publishing the unminified file to the CDN I'll try to look into this).

**Comment by asimihsan** [comment]
`jsdelivr` have a new commit bot that prohibits pull requests that modify the file structure of projects. This means I can't use `jsdelivr` to publish both the minified and non-minified versions of `tablequeryjs`.

I'm re-using old scripts to publish this to my [AWS CloudFront](http://aws.amazon.com/cloudfront/details/) backed `files.asimihsan.com` CDN. It's pretty cheap and I have enough free credits from programming contests for this to be free for a few years.

A tangential advantage of this approach is that I can use [Zopfli](https://code.google.com/p/zopfli/) to reduce the final gzip'd size by 4% beyond what gzip level 9 can achieve.

**Comment by asimihsan** [comment]
nm `jsdelivr` just manually accepted my pull request.

**Comment by asimihsan** [comment]
Fixed by v0.1.6 release, please see https://github.com/asimihsan/tablequeryjs/releases/tag/v0.1.6.

**Comment by drothlis** [comment]
Thanks for the quick fix!
